#!/bin/bash

PROJECT=$1
SOURCE_DIR=bf-src

export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"
export LESS=' -R -N '

case $PROJECT in
    rot13|hello|triangle) echo "'$PROJECT' demo selected";;
    *)  echo   "Usage: $0 DEMO"
        echo   "Execute the given DEMO, where DEMO is"
        echo   "    rot13    - ROT13 (caesar) en/decoder"
        echo   "    hello    - Hello World"
        echo   "    triangle - Sierpinski triangle on 80-column display"
        exit -1;;
esac

SOURCE="$SOURCE_DIR/$PROJECT.bf"

clear
echo ""
figlet -ct -f banner "Brainf*** to Hardware"
echo "With PandA Bambu & yosys/arachne-pnr/icestorm"
read

clear
echo "**************************************************************"
echo "Showing original BF code... "
echo "**************************************************************"
read

less $SOURCE

# Build BF to C converter
gcc -o bf2c.exe bf2c/bf2c.c -DMEMORY_SIZE=256

if [ $? != 0 ]; then
    echo "gcc failed"
    exit -1
fi

clear
echo "**************************************************************"
echo "Translating BF code to C"
echo "**************************************************************"
read

# Convert BF source to C
./bf2c.exe  < $SOURCE > bf2c_bambu_main.c 

clear
echo "**************************************************************"
echo "Showing C translation of BF code... "
echo "**************************************************************"
read

less bf2c_bambu_main.c

if [ $? != 0 ]; then
    echo "bf2c failed"
    exit -1
fi

clear
echo "**************************************************************"
echo "Running Bambu C-to-Verilog HLS"
echo "**************************************************************"
read

# Run Bambu
./bambu.sh

if [ $? != 0 ]; then
    echo "bambu failed"
    exit -1
fi

clear
echo "**************************************************************"
echo "Showing Verilog code generated by Bambu HLS... "
echo "**************************************************************"
read

less synth/top.v

clear
echo "**************************************************************"
echo "Running FPGA flow (yosys+arachne-pnr+icestorm) "
echo "**************************************************************"
read

# Run Yosys/Arachne/icepack
rm -f impl-hx8k/*.mem
touch impl-hx8k/array.mem
find synth -iname '*.mem' -exec cp {} impl-hx8k \;
make -C impl-hx8k bf2hw.bin
mv impl-hx8k/bf2hw.bin "impl-hx8k/$PROJECT.bin"

if [ $? != 0 ]; then
    echo "fpga flow failed"
    exit -1
fi

clear
echo "**************************************************************"
echo "Showing bitstream implemented by yosys/arachne-pnr/icestorm... "
echo "**************************************************************"
read

less impl-hx8k/bf2hw.asc

clear
echo "**************************************************************"
echo "Downloading bitstream, starting terminal "
echo "**************************************************************"
read

./comm.sh $PROJECT

